<?php
/**
 * @author    XE Developers <developers@xpressengine.com>
 * @copyright 2015 Copyright (C) NAVER Corp. <http://www.navercorp.com>
 * @license   http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html LGPL-2.1
 * @link      https://xpressengine.io
 */

namespace Xpressengine\Tests\Plugin;
use Xpressengine\Plugin\AbstractPlugin;

class AbstractPluginTest /*extends \PHPUnit\Framework\TestCase*/
{

    /**
     * @var AbstractPlugin
     */
    protected $plugin;

    protected function tearDown()
    {
        \Mockery::close();
        parent::tearDown();
    }

    public function testGetPluginInfo()
    {
        $info = $this->plugin->getPluginInfo();

        $this->assertEquals(count($info), 6);
        $this->assertEquals($info['Name'], '플러그인명');
        $this->assertEquals($info['Version'], '3.0.2.2');
    }

    public function testGetPluginId()
    {
        $info = $this->plugin->getPluginId();

        $this->assertEquals($info, 'plugin_sample');
    }

    protected function setUp()
    {
        require_once __DIR__.'/plugins/plugin_sample/plugin.php';

        $this->plugin = new \Xpressengine\Tests\Plugin\Sample\PluginSample();

        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
